<?php

/**
 * @file
 * Module file for geospatial module.
 */

//define('SPATIAL_FILE_GROUPING_COLLECTION', 0);
//define('SPATIAL_FILE_GROUPING_MULTIPLE', 1);
//define('SPATIAL_FILE_GROUPING_BYTYPE', 2);

/**
 * Implements hook_ctools_plugin_directory
 *
 * Tell ctools where to find plugins.
 */
function geospatial_ctools_plugin_directory($owner, $plugin_type) {
  return 'plugins/' . $plugin_type;
}

/**
 * Implements hook_permission().
 */
function geospatial_permission() {
  return array(
    'administer geospatial' => array(
      'title' => t('Administer GeoSpatial'),
      'description' => t('Access administration pages and settings related to the GeoSpatial module.'),
    ),
  );
}

/**
 * Implement hook_menu().
 */
function geospatial_menu() {
  $items = array();

  $items['admin/config/content/geospatial'] = array(
    'title' => 'GeoSpatial',
    'description' => 'Configure GeoSpatial settings and ogr2ogr options.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('geospatial_admin_settings'),
    'access arguments' => array('administer geospatial'),
    'file' => 'includes/geospatial.admin.inc',
  );

  return $items;
}

/**
 * Get the ogr2ogr path...
 */
function get_ogr2ogr_bin_path() {
  // If the ogr2ogr variable hasn't been configured, attempt to find it with `which`.
  $path = variable_get('geospatial_ogr2ogr_path', exec('which ogr2ogr'));
  return $path;
}
